import { useState } from 'react'
import { ArrowRight, Building2, Handshake, MapPin, Search, ShieldCheck, KeyRound } from 'lucide-react'
import { Link, Navigate, useLocation, useParams } from 'react-router-dom'
import properties from '../data/properties.json'
import projects from '../data/projects'
import { filterProperties, filtersFromSearch, puneWestLocations } from '../lib/properties'
import PropertyGrid from '../components/PropertyGrid'
import PropertyFilters from '../components/PropertyFilters'
import PropertyGallery from '../components/PropertyGallery'
import PropertyDetails from '../components/PropertyDetails'
import EnquiryForm from '../components/EnquiryForm'
import { CallButton, WhatsAppButton } from '../components/Actions'

function useFilters() { const { search } = useLocation(); const [filters, setFilters] = useState(() => filtersFromSearch(search)); return [filters, (key, value) => setFilters({ ...filters, [key]: value })] }
export function HomePage() { const [filters, change] = useFilters(); const featured = properties.filter((item) => item.featured).slice(0, 6); return <><section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">Pune West real estate</p><h1>Find Your Dream Property in Pune</h1><p>Discover the right home, investment and commercial property with Right Key Properties.</p><div className="hero-actions"><Link className="btn btn-gold" to="/buy">Explore Properties <ArrowRight size={17} /></Link><Link className="btn btn-outline" to="/sell">Sell Your Property</Link></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1400&q=85" alt="Contemporary Pune home exterior" /></div></div></section><section className="shell search-panel"><p className="eyebrow">Begin your search</p><PropertyFilters filters={filters} onChange={change} onSubmit={(event) => { event.preventDefault(); const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); window.location.hash = `/buy?${params}` }} /></section><Section title="Featured demo properties" copy="A considered selection of sample listings to help you explore Pune West."><PropertyGrid properties={featured} /></Section><Section title="Explore Pune West" copy="Choose a location to begin a more focused property search."><div className="location-grid">{puneWestLocations.map((location) => <Link key={location} to={`/buy?location=${location}`}><MapPin size={18} /> {location}<ArrowRight size={17} /></Link>)}</div></Section><Section title="Why choose Right Key Properties"><div className="service-grid">{[[Search, 'Property Search Assistance', 'A clearer route through your options.'], [Handshake, 'Site Visit Assistance', 'Thoughtful support while exploring.'], [KeyRound, 'Buying Assistance', 'Guidance from shortlist to decision.'], [Building2, 'Selling Assistance', 'A considered approach to listing.']].map(([Icon, title, copy]) => <article key={title}><Icon /><h3>{title}</h3><p>{copy}</p></article>)}</div></Section><section className="seller"><div className="shell"><div><p className="eyebrow">For owners</p><h2>Thinking About Selling Your Property?</h2><p>Tell us about your property and start the conversation.</p></div><Link className="btn btn-gold" to="/sell">List Your Property <ArrowRight size={17} /></Link></div></section></> }
function Section({ title, copy, children }) { return <section className="shell section"><div className="section-head"><div><p className="eyebrow">Right Key Properties</p><h2>{title}</h2>{copy && <p>{copy}</p>}</div></div>{children}</section> }
export function ListingPage({ intent }) { const [filters, change] = useFilters(); const list = filterProperties(properties, { ...filters, intent }); return <Section title={intent === 'buy' ? 'Buy property in Pune West' : 'Rent property in Pune West'} copy="Every listing shown is demo content for this website."><PropertyFilters compact filters={filters} onChange={change} onSubmit={(event) => event.preventDefault()} /><p className="results">{list.length} demo {list.length === 1 ? 'property' : 'properties'} found</p><PropertyGrid properties={list} /></Section> }
export function PropertyPage() { const { id } = useParams(); const property = properties.find((item) => item.id === id); if (!property) return <Navigate to="/buy" replace />; return <main className="shell detail-page"><PropertyGallery property={property} /><div className="detail-grid"><PropertyDetails property={property} /><aside><WhatsAppButton property={property} className="full" /><CallButton className="full" /><EnquiryForm subject={`Enquiry about ${property.name}`} /></aside></div></main> }
export function SellPage() { return <Section title="Sell your property with clarity" copy="Share the basics and a Right Key Properties representative can contact you when details are available."><div className="split"><div className="copy-block"><ShieldCheck size={34} /><h3>Considered selling assistance</h3><p>We help you begin with the information that matters: property type, location, and your preferred next step.</p></div><EnquiryForm subject="List your property" /></div></Section> }
export function ProjectsPage() { return <Section title="Demo projects in Pune West" copy="Project profiles below are sample content for this launch."><div className="project-grid">{projects.map((project) => <article key={project.id} className="project-card"><img src={project.image} alt={`${project.name} sample ${project.type} in ${project.location}`} /><div><p className="eyebrow">Demo project · {project.location}</p><h3>{project.name}</h3><p>{project.description}</p><Link className="text-link" to={`/projects/${project.id}`}>View project <ArrowRight size={16} /></Link></div></article>)}</div></Section> }
export function ProjectPage() { const { id } = useParams(); const project = projects.find((item) => item.id === id); if (!project) return <Navigate to="/projects" replace />; return <section className="shell section"><img className="project-hero" src={project.image} alt={`${project.name} sample project in ${project.location}`} /><p className="eyebrow">Demo project · {project.location}</p><h1>{project.name}</h1><p className="lede">{project.description}</p><ul className="highlights">{project.highlights.map((item) => <li key={item}>{item}</li>)}</ul><EnquiryForm subject={`Enquiry about ${project.name}`} /></section> }
export function AboutPage() { return <Section title="A more considered property search" copy="Right Key Properties focuses on helping buyers, renters, owners, and investors explore Pune West with clarity. This website is an introduction to the service approach; no performance claims are made here."><div className="copy-block"><h3>How we can help</h3><p>From refining a property brief and arranging a site visit to supporting a sale conversation, the focus is on practical next steps that suit your situation.</p><Link className="btn btn-dark" to="/contact">Contact us</Link></div></Section> }
export function ContactPage() { return <Section title="Let’s talk property" copy="Contact information will be added here shortly. You can still tell us what you are looking for through the enquiry form."><div id="contact" className="split"><div className="contact-panel"><MapPin size={32} /><h3>Pune West</h3><p>Baner · Balewadi · Wakad · Hinjewadi · Tathawade · Punawale · Mahalunge · Bavdhan</p><CallButton /></div><EnquiryForm /></div></Section> }
